model:
  name: legal-bert
  pretrained_model: "nlpaueb/legal-bert-base-uncased"
  num_labels: 5
  max_length: 512
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1

training:
  batch_size: 16
  learning_rate: 2e-5
  num_epochs: 10
  warmup_steps: 500
  weight_decay: 0.01
  gradient_accumulation_steps: 2
  max_grad_norm: 1.0
  
  # Mixed precision training
  fp16: true
  fp16_opt_level: "O1"

data:
  train_file: "data/processed/train.jsonl"
  val_file: "data/processed/val.jsonl"
  test_file: "data/processed/test.jsonl"
  cache_dir: "data/cache"
  
evaluation:
  metrics:
    - accuracy
    - f1
    - precision
    - recall
  save_predictions: true
  prediction_output_dir: "predictions" 